//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management_System_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberHasMembership
    {
        public System.Guid MemberID { get; set; }
        public int MembershipID { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime JoinDate { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Membership Membership { get; set; }

        public static implicit operator Membership(MemberHasMembership v)
        {
            throw new NotImplementedException();
        }
    }
}
