//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management_System_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public System.Guid PaymentID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public decimal Amount { get; set; }
        public string PaymentMethod { get; set; }
        public System.Guid MemberID { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
